language: go
# sudo: false
sudo: required
os:
  - linux
  - osx
go:
  - 1.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master
env:
  - GO_ARCH=amd64
  - GO_ARCH=386
  - GO_OS=windows GO_ARCH=amd64
  - GO_OS=windows GO_ARCH=386
  - GO_OS=darwin GO_ARCH=amd64
matrix:
  exclude:
    - os: osx
      env: GO_ARCH=386
    - os: osx
      env: GO_OS=windows GO_ARCH=amd64
    - os: osx
      env: GO_OS=windows GO_ARCH=386
    - os: osx
      env: GO_OS=darwin GO_ARCH=amd64
  allow_failures:
      - go: master
      - go: 1.7.x
      - os: osx
before_install:
  - export GOARCH=$GO_ARCH
  - export GOOS=$GO_OS
  - export PATH=${PATH}:${GOPATH}/bin/:${GOPATH}/bin/`go env GOOS`_`go env GOARCH`/
  - go env
  - export
  - if [[ "$TRAVIS_OS_NAME" != "linux" ]]; then cat /proc/meminfo /proc/cpuinfo; fi
  - if [[ -z "$GOOS" ]]; then go get github.com/mattn/goveralls; fi # only native builds can be covered
script:
  - if [[ -n "$GOOS" ]]; then travis_wait 30 go build -v ./... ; fi # only native builds can be covered
  - if [[ -z "$GOOS" ]]; then travis_wait 30 goveralls -service travis-ci ; fi # only native builds can be covered
